### ISSUE TITLE
Show Office Fabric UI - React - Tabbed

### ISSUE THREAD

**Issue by FreeSoftwareServers** [OfficeDev/Excel-Add-in-JavaScript-SalesTracker#10]
This example add-in is a great reference to using a tab bar. I chose it as my template for Add Ins. Im getting close to doing a demo for work but I'd prefer to use the current Fabric UI w/ React which is was MS is pushing.

Can you do a seperate clone of this project utilizing React so people can compare or update this project to use React?!

The tabbed interface is amazing BTW!

**Comment by Rick-Kirkham** [comment]
Glad that you like it. I will make an item for your request internally. 
Now the bad news: Realistically, it is unlikely we will ever get to this work item. You would have better luck asking the Fluent UI (which is the new name of Fabric UI) team to create a tab bar control. To do that, start at [Fluent UI (React)](https://developer.microsoft.com/en-us/fluentui#/controls/web). Scroll down to the section **Need a control you don't see here?**. 

Since we're tracking this request internally, I'll close this issue. 

Thanks, again, for your interest.
