### ISSUE TITLE
Missing Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props

### ISSUE THREAD

**Issue by bradbase** [OfficeDev/Excel-Add-in-JavaScript-SalesTracker#8]
I am getting an error while building this project in VS 2019.

I have got both the NuGet package manager Package Restore checkboxes checked. (eg; Allow NuGet to download missing packages, and Automatically check for missing packages during build in Visual)

Removing Target EnsureNuGetPackageBuildImports from the SalesTrackerWeb.csproj allows the project to build but I don't accept that as an appropriate fix.

```
1>------ Build started: Project: SalesTrackerWeb, Configuration: Debug Any CPU ------
1>C:\Users\bradb\Documents\Yeo_Excel\Excel-Add-in-JavaScript-SalesTracker\SalesTrackerWeb\SalesTrackerWeb.csproj(163,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.1\build\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props.
2>------ Build started: Project: SalesTracker, Configuration: Debug Any CPU ------
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by WayneVSDev** [comment]
I face the same issue, I follow your practice to remove EnsureNuGetPackageBuildImports node from the SalesTrackerWeb.csproj, then the project is able to compile, but after running, the "Sales Tracker" button is missing from the Home Ribbon.

Any update from the development team on this issue?

**Comment by Rick-Kirkham** [comment]
@bradbase I can reproduce the original error about the missing package. Doctoring the *.csproj file as you suggested is actually the best possible solution. The reason is that this particular add-in does not have any server-side code, and hence does not use the .NET compiler. The project was created with the Office project template in Visual Studio, which assumes that the add-in is going to have a server-side that uses .NET code. 

I will make your suggested edit and push it to the repo.

@WayneVSDev  I cannot reproduce the issue about the missing button, which is called **Track Sales**, not **Sales Tracker**.
